### ISSUE TITLE
Error loading this mod

### ISSUE THREAD

**Issue by clommm** [Rune580/LethalCompanyInputUtils#10]
![image](https://github.com/Rune580/LethalCompanyInputUtils/assets/64776077/bd0e9f33-d4ef-4643-b9ba-3a62ed7d82b8)
Hi there, got this in the command prompt when loading up lethal company. Not sure what is wrong

**Comment by Rune580** [comment]
Out curiosity what version of the game are you running?

**Comment by clommm** [comment]
v45

**Comment by Rune580** [comment]
can you send a full log and a modpack code?

**Comment by clommm** [comment]
Code: 018d0234-dd1f-9528-ad35-92644f430305
[LogOutput.log](https://github.com/Rune580/LethalCompanyInputUtils/files/13927962/LogOutput.log)

**Comment by Rune580** [comment]
Are you sure you're running v45, I can't get the error to happen on my end

**Comment by clommm** [comment]
you mean the mod works for you

**Comment by Rune580** [comment]
well, yes. Can you send a screenshot of the main menu? like so
![image](https://github.com/Rune580/LethalCompanyInputUtils/assets/12521934/5bc61363-8d0b-420a-8c8a-816c8f3fc38a)

**Comment by clommm** [comment]
![image](https://github.com/Rune580/LethalCompanyInputUtils/assets/64776077/290143be-670c-4ca5-8621-7ca01214d789)

**Comment by Rune580** [comment]
hmnm, try updating InputUtils to 0.5.2 and see if the error still occurs, otherwise not much I can do. I'm only really targeting the latest version of the game.

**Comment by clommm** [comment]
hi dude it worked thanks a lot
