### ISSUE TITLE
InputUtils fails to run on latest version.

### ISSUE THREAD

**Issue by DxsSucuk** [Rune580/LethalCompanyInputUtils#11]
I am running on v47 in a modpack with all most disabled.
![image](https://github.com/Rune580/LethalCompanyInputUtils/assets/53257574/e23e59ba-0a0e-4c14-a110-35d87cc49d58)

Using R2Modman to manage the modpack here is the code if needed: 018d040f-5d71-8d8c-2f27-e3c0e735f857

**Comment by DxsSucuk** [comment]
To clarify, I can start the game but the keybinds menu does not work anymore because the prefab can not be loaded.

**Comment by Rune580** [comment]
Alright I'm on it right now

**Comment by Rune580** [comment]
just pushed 0.5.1, give it a minute to show on the thunderstore

**Comment by Rune580** [comment]
let me know if the issue is still present

**Comment by Rune580** [comment]
Tested modpack with 0.5.1 error is no longer present

**Comment by DxsSucuk** [comment]
Can confirm works fine for me too!
