### ISSUE TITLE
Unbinding Key Bug

### ISSUE THREAD

**Issue by ChaosKronorium** [Rune580/LethalCompanyInputUtils#13]
Unbinding normal lethal company keys causes a bug for the ui to get stuck not allowing to exit the menu.

**Comment by Rune580** [comment]
I'm looking into this right now.

**Comment by Rune580** [comment]
found what's causing the issue, hotfix soon.

**Comment by Rune580** [comment]
Sorry for the wait, this one was tricky to fix. but I'm testing the fix right now

**Comment by Rune580** [comment]
tested and working, let me know if 0.5.5 fixed the issue for you

**Comment by ChaosKronorium** [comment]
Thank you its fixed!
