### ISSUE TITLE
just want to know how to install manually

### ISSUE THREAD

**Issue by drink1101** [Rune580/LethalCompanyInputUtils#14]
me and my friends are in china so not everyone can use mod manager, i just want to know what's that AssetBundles/ui-assets for, i can't find it the the profile, do i need this put somewhere?

**Comment by Rune580** [comment]
Sorry, for the wait. The mod can be installed manually by extracting the `plugins` folder inside the zip to the BepInEx directory, merging folders as needed

**Comment by drink1101** [comment]
ok thank you
