### ISSUE TITLE
Version 0.5.0 and up causing massive stuttering

### ISSUE THREAD

**Issue by NovaNoidle** [Rune580/LethalCompanyInputUtils#15]
Hello I just wanted to report that version 0.5.0 and all the latest versions are causing my game to lag and stutter, if I roll it back to version 0.4.4 everything is back to normal and there is no issue, this seems to be a compatibility issue between this mod and HDLethalCompany as when that is disabled it works normally. if you need any information from me let me know

I'm not too sure if this is an issue on my end or not so I'm going to close this and investigate on my end a bit

**Comment by Rune580** [comment]
I'm sorry, I've just now seen this issue here. What is it that you're asking about?
