### ISSUE TITLE
Join servers

### ISSUE THREAD

**Issue by unluckyjori** [Rune580/LethalCompanyInputUtils#19]
It used to let me join servers but after I updated it I get an error joining them. I tried downloading a old version but for some reason it won’t let me anymore.

**Comment by Rune580** [comment]
This doesn't seem to be related to InputUtils, but just in-case, send logs + modpack code

**Comment by unluckyjori** [comment]
it works without the mod and when I add it it dose not

**Comment by unluckyjori** [comment]
018d3d46-662f-e880-b54d-317484b1c68d

**Comment by unluckyjori** [comment]
[Info   : Unity Log] Disconnect callback called
[Info   : Unity Log] Is server: False; ishost: False; isConnectedClient: False
[Info   : Unity Log] Local client connection denied; clientId: 0; reason:
[Info   : Unity Log] Displaying menu message
[Info   : Unity Log] Failed loading; displaying notification
[Info   : Unity Log] result: Error

**Comment by Rune580** [comment]
are you joining public lobbies or a friends server?

**Comment by unluckyjori** [comment]
public

**Comment by Rune580** [comment]
generally speaking, you need to have the same mod list as the host of public lobbies. InputUtils has nothing to with this as it's a client side only mod. As proof, here's a video of me hosting and join a lobby I created with your modpack

https://github.com/Rune580/LethalCompanyInputUtils/assets/12521934/fc869bfc-1574-490c-9a79-078dfd73b494

**Comment by unluckyjori** [comment]
when I try to join a lobby without the same mods as me it works normaly but when I add the mod it wont let me join

**Comment by unluckyjori** [comment]
host the lobby without any mods and join the lobby with the modpack

**Comment by Rune580** [comment]
Looking through a few mods in the list, a few of them do a mod list check and cancel the connection if they do not match. I've checked the log and found that this is in fact the case. For future reference InputUtils doesn't touch anything network related and shouldn't ever be the case of you not being able to load into a lobby. Unless another mod is doing a modlist check.
