### ISSUE TITLE
Unable to join room

### ISSUE THREAD

**Issue by stuwaper** [Rune580/LethalCompanyInputUtils#24]
Opening InputUtils will significantly reduce the probability of me joining other passersby's rooms, perhaps because others have not installed the same mod,do I need to install any other modules?

**Comment by DeathWrench** [comment]
Uninstall this mod, other mods that use it as a dependency may still work without it albeit a bit buggier, and you'll be able to join people again.

**Comment by DeathWrench** [comment]
There's a lot less mods that cause this issue then there are mods that do. Here's the mods off the top of my head that cause this. Enhanced Lockpicker, Runtime Netcode Patcher, Roomba Landmines, and Sell My Scrap
Having 100+ mods installed currently and am still able to join public lobbies and play just fine with no issues. If you don't plan on fixing it. At the very least, you could put a disclaimer that says nobody will be able to join your session unless they also have this installed.

**Comment by Rune580** [comment]
It's not that I don't want to fix it, it's that It's literally out of my control.
