### ISSUE TITLE
Not working on version Lethal Company v49

### ISSUE THREAD

**Issue by freezaer** [Rune580/LethalCompanyInputUtils#27]
Read and fill in the following:

- [x] I use r2modman/thunderstore.

- [х] I acknowledge that issues from manual installs may not get resolved as they are difficult for mod developers to debug.

- [х] I acknowledge that InputUtils only officially supports the latest version of Lethal Company.

- [х] I acknowledge that this issue may be closed if all players in the lobby don't have the exact same mod list and versions.

- [х] I have filled or marked all fields marked with `<!-- Required -->` including this checkbox and acknowledge that failure to do so may result in my issue being closed immediately and deleted in 24 hours if I fail to fill or mark the required fields. Failure to mark this checkbox **Doesn't** mean you can ignore the requirements.

---

**Versions**
InputUtils Version:  ex: 0.6.0
Lethal Company Version: ex: v49

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Please attach any relevant logs, this makes it far easier for us to fix your issue.
Finding Logs (r2modman/thunderstore):
1. Go to your profile in r2modman/thunderstore.
2. Click `Settings>Locations>Browse profile folder`
3. Open the `BepInEx` folder
4. The log file we want is called `LogOutput.log`

**ModPack Code or File**

**Additional context**

**Comment by Rune580** [comment]
You need to actually fill out the required fields you know :/

Closing for now, if you edit it and fill out the fields correctly, I'll re-open it.
