### ISSUE TITLE
[Bug]: conflict loading assetbundle folder

### ISSUE THREAD

**Issue by Gianmarcofaggi** [Rune580/LethalCompanyInputUtils#30]
### Acknowledgements

- [X]  I use r2modman/thunderstore and will provide a modpack code or zip
- [X] I understand that InputUtils only officially supports the latest version of Lethal Company

### Lobby Related

No

### Lobby Acknowledgements

- [ ] I understand that all players must have the exact same mod list and have made sure that all players have the exact same modlist.

### InputUtils Version

latest

### Game Version

v49

### Describe the bug

the mod requires to load ui-assets from the assetbundle folder, but the folder is already used for another mod (in my case  custom emotes API with badass company). this causes the emote mod to not load any emotes.

### Reproduction steps

the mod requires to load ui-assets from the assetbundle folder, but the folder is already used for another mod (in my case  custom emotes API with badass company). this causes the emote mod to not load any emotes.

### ModPack code or file

.

### Logs

 error log (i used other emote mods like Glizzyemotemod) :
[Error  : Unity Log] The AssetBundle 'J:\Giochi\downloads\Lethal.Company.v49\Lethal.Company.v49\BepInEx\plugins\assetbundles\ui-assets' can't be loaded because another AssetBundle with the same files is already loaded.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Glizzy.Assets.LoadAssetBundlesFromFolder (System.String folderName) (at <046cc3f563d54997a68e6987929dbe54>:0)
Glizzy.GlizzyEmoteMod.Awake () (at <046cc3f563d54997a68e6987929dbe54>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

**Comment by Rune580** [comment]
You aren't using r2modman despite claiming as much in the acknowledgements.

Make sure all mods are installed in their own sub-folder withing the `plugins` folder.
