### ISSUE TITLE
Show/Hide Purchasable Shotgun/Shells In The Store?

### ISSUE THREAD

**Issue by jbrivers7** [Rune580/LethalCompanyInputUtils#36]
Would it be possible to, while the game has already been started, have an Enabled/Disabled BepInEx configuration button that allows you to Show/Hide the Shotgun/Shells in the store? In the case that you want to turn it off for a regular game experience or turn it on at will for a fun experience. Thank you VERY much for your time!

**Comment by Rune580** [comment]
This repo is for InputUtils, a mod that allows mod devs to add custom controls to the game. I think you might be lost.

**Comment by jbrivers7** [comment]
My apologies sir, you are correct. I had two tabs opened, and posted in the wrong one. Sorry about that.
