### ISSUE TITLE
[Question] Anyway to have non constant default keys?

### ISSUE THREAD

**Issue by KlutzyBubbles** [Rune580/LethalCompanyInputUtils#4]
i want to load defaults from a config, but the default keys for the annotations are required to be constants at compile, and because i am not very experienced with all of this i don't know where to look to see if its possible.

**Comment by Rune580** [comment]
next update will be adding a way to create input actions at runtime rather than compile time.

**Comment by Rune580** [comment]
should be out within 24 hours

**Comment by Rune580** [comment]
there's now a runtime api starting with v0.4.0
