### ISSUE TITLE
[Bug]: Error on startup

### ISSUE THREAD

**Issue by Teals53** [Rune580/LethalCompanyInputUtils#46]
### Acknowledgements

- [X] I use r2modman/thunderstore and will provide a modpack code or zip
- [X] I understand that InputUtils only officially supports the latest version of Lethal Company

### Lobby Related

No

### Lobby Acknowledgements

- [X] I understand that all players must have the exact same mod list and have made sure that all players have the exact same modlist.

### InputUtils Version

0.7.4

### Game Version

v50

### Describe the bug

Error on startup

### Reproduction steps

Open Game

### ModPack code or file

.

### Logs

[Error  : Unity Log] ArgumentException: Type 'Keyboard' has not been registered as a control layout
Parameter name: type
Stack trace:
UnityEngine.InputSystem.InputManager.TryLoadControlLayout (System.Type type) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:IL_0071)
UnityEngine.InputSystem.InputSystem.LoadLayout[TControl] () (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:IL_0000)
LethalCompanyInputUtils.Utils.LayoutExporter..cctor () (at /home/runner/work/LethalCompanyInputUtils/LethalCompanyInputUtils/LethalCompanyInputUtils/Utils/LayoutExporter.cs:12)
Rethrow as TypeInitializationException: The type initializer for 'LethalCompanyInputUtils.Utils.LayoutExporter' threw an exception.
LethalCompanyInputUtils.LethalCompanyInputUtilsPlugin.Awake () (at /home/runner/work/LethalCompanyInputUtils/LethalCompanyInputUtils/LethalCompanyInputUtils/LethalCompanyInputUtilsPlugin.cs:50)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

**Comment by Rune580** [comment]
The error is caused by a debugging utility I left in and forgot to fix. It doesn't cause any issue however as it only breaks the debug utility itself. I've fixed this in the commit 2f74ee2edc65c63d220ed02be344bb254eca7bc5. I've not yet released the fix as it's a harmless error.

**Comment by Rune580** [comment]
Fix is present in release 0.7.5
