### ISSUE TITLE
[Bug]: host button not working

### ISSUE THREAD

**Issue by Lepipae** [Rune580/LethalCompanyInputUtils#51]
### Acknowledgements

- [X] I use r2modman/thunderstore and will provide a modpack code or zip
- [X] I understand that InputUtils only officially supports the latest version of Lethal Company

### Lobby Related

Yes

### Lobby Acknowledgements

- [X] I understand that all players must have the exact same mod list and have made sure that all players have the exact same modlist.

### InputUtils Version

0,7,5

### Game Version

v50

### Describe the bug

in this new version of the mod the host and quit buttons on the main menu are not working, when i downgrade the mod to the v0.7.4 it does work

### Reproduction steps

boot up the game
click the online button to enter the main menu

### ModPack code or file

018ff85a-6d1a-c7d6-cf71-b78489cd951b

### Logs

[LogOutput.log](https://github.com/user-attachments/files/15748607/LogOutput.log)

**Comment by Rune580** [comment]
Forgot to include AssetBundles with 0.7.5, just pushed out 0.7.6 which fixes this.
