### ISSUE TITLE
[Bug]: Chip bags are 100lbs of weight / disappearing after latest patch

### ISSUE THREAD

**Issue by Precisi** [Rune580/LethalCompanyInputUtils#53]
### Acknowledgements

- [X] I use r2modman/thunderstore and will provide a modpack code or zip
- [X] I understand that InputUtils only officially supports the latest version of Lethal Company

### Lobby Related

No

### Lobby Acknowledgements

- [X] I understand that all players must have the exact same mod list and have made sure that all players have the exact same modlist.

### InputUtils Version

??

### Game Version

v55

### Describe the bug

There's a problem with casino chip bags being 100lbs of invisible weight. They also disappear after reloading the saved game. 

Everything was fine when we played v55 in beta, but when it went live things are now broken. 

### Reproduction steps

We went to the casino, exchanged bags for chips, and upon dropping the chip bag were 100lbs heavier on our character. If you pick a bag back up you are back at 0 lbs.

We all reconnected but upon reloading the save file all the bags of chips had vanished from our ship. However, our weight was also reset. 

### ModPack code or file

01908a92-0f4b-d9db-4474-ff471ecb5903

### Logs

[LogOutput.log](https://github.com/user-attachments/files/16117713/LogOutput.log)

**Comment by ToastedOven** [comment]
chat is this the correct mod for casino problems

**Comment by Precisi** [comment]
> chat is this the correct mod for casino problems

Oh geez, I'm sorry. It's not. I misclicked.

**Comment by Rune580** [comment]
I'm 99% sure you have the wrong mod, InputUtils is for rebinding modded keybinds, lmao

**Comment by Precisi** [comment]
I'm so so sorry! :(

Easiest bug to fix ever?? ;)
(I can't delete this)
