### ISSUE TITLE
Add keybinds to dedicated "Mod Keybinds" section

### ISSUE THREAD

**Issue by legoandmars** [Rune580/LethalCompanyInputUtils#6]
I think it's a good idea to have separation between vanilla and modded keybinds so people don't get them confused

There's already a `REBIND CONTROLLERS` section, so the system seems like it's in place

Could go between the main section and `REBIND CONTROLLERS` section

**Comment by Rune580** [comment]
There isn't a "section" system in place with the in-game ui, when loading the rebind menu, it loads every bind until it reaches the controller binds and then before reaching the first controller bind it adds the text `REBIND CONTROLLERS` to the ui.

I can certainly modify the UI as a whole to make up for this, but that could potentially break compatibility with any mods that opt for implementing their own system for add binds to the game ui.

I'll think about it

**Comment by Rune580** [comment]
#9 Added this. I'll close this issue once this is available in the latest release

**Comment by legoandmars** [comment]
Preview looked great, good stuff

**Comment by Rune580** [comment]
doing some final compat testing with mods that inject their controls directly into the keybinds UI bypassing InputUtils. If everything goes well I should have a release here soon

**Comment by Rune580** [comment]
implemented with 0.5.0
