### ISSUE TITLE
0.4.3 Breaks my mods keybinds

### ISSUE THREAD

**Issue by KlutzyBubbles** [Rune580/LethalCompanyInputUtils#7]
Hi, not sure if its the way i have implemented it or if something changed im just not familiar with but i had a lot of reports of my mod just not working after you pushed an update.

Tested it on my machine and 0.4.2 works fine, but 0.4.3 makes keybdings no functional (although they still appear in the settings menu).

You can see my implementation here https://github.com/KlutzyBubbles/lc-better-emotes

I am hoping you could quickly look and see if there is anything obvious because i dont have my computer to run changes or logging to test what is and isnt working. If i have jumped the gun and the issue is somewhere else i apologise, but i only changed the InputUtils mod version and nothing else.

**Comment by Rune580** [comment]
Looks like it was my fault, I changed Assets to be a public property instead of a protected field, and that seemed to have messed with the IL side of things, simply compiling your mod against the latest version of input utils should fix it

**Comment by Rune580** [comment]
Sorry to cause unnecessary trouble for you

**Comment by KlutzyBubbles** [comment]
> Sorry to cause unnecessary trouble for you

All good, didnt realise it was an easy fix like that (well hopefully). Just caught me off guard when i started getting messages about the mod not working when i hadnt updated in days lmao.
