### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by alkingshefo** [Rune580/LethalCompanyInputUtils#8]
the latest Version does not work with InfiniteEmote, and breaks More Emotes making me unable to move, move in my place, in the ship, i had to downgrade to 4.2 and it works perfectly now, i am using Thunderstore mod manager.
maybe they just need to update their mods, i just wanted to inform you about the problem^^

**Comment by Rune580** [comment]
What version of those mods were you using? and if you have the logs from then, those would be appreciated

**Comment by alkingshefo** [comment]
Sorry i took a while to reply, i honestly don't know which logs exactly or the best way to upload them. testing out few things made me realize the problem is with Infinite Emotes version 1.2.1, pairing it with Input 4.4 i can see the rebinding button in settings but it does not work when i click it. Bepenix logs for show an error here 
[Logs 4.4-infi niteemote1.2.1.txt](https://github.com/Rune580/LethalCompanyInputUtils/files/13850885/Logs.4.4-infi.niteemote1.2.1.txt)
With the previous version that error is not there, shown in this log 
[Logs 4.2.txt](https://github.com/Rune580/LethalCompanyInputUtils/files/13850891/Logs.4.2.txt)
as for More emotes it turned out to be working fine alone with version 4.4 but using Infinite Emotes along with More Emotes with Utility 4.4 results in not just unable to stop emotes but i can't move at all from spawning location. Logs are here
[InfiniteEmote with emotes.txt](https://github.com/Rune580/LethalCompanyInputUtils/files/13850894/InfiniteEmote.with.emotes.txt)

**Comment by alkingshefo** [comment]
InfiniteEmote just update the mod to be compatible with the latest version, Thank you for your time <3
